#!/bin/bash
#SBATCH --job-name=test_full      # Job name
#SBATCH --mail-type=ALL              # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=3gmichels@gmail.com    # Where to send mail	
#SBATCH --nodes=1                    # Run all processes on a single node	
#SBATCH --ntasks=1                   # Run a single task		
#SBATCH --cpus-per-task=1            # Number of CPU cores per task
#SBATCH --mem=30gb                   # Job memory request
#SBATCH --time=00:02:30              # Time limit hrs:min:sec 8:0:0
#SBATCH --gres=gpu:1				 # Amount of GPUs
#SBATCH --output=slurm-full_hazik_eval_base-%j.out  # Output name

pwd; hostname; date

echo "Evaluating Haziq's model"

module purge
module load gcc/8.4.0-cuda python/3.7.7
source /home/michels/venvs/haziq/bin/activate

model="190525-002719" #"210406-113617"
epoch_nb="6" #"2"

srun python3 -m openpifpaf.eval --batch-size 1 --jaad_batch_size 1 \
--checkpoint outputs/resnet50block5-pif-paf-crm-edge401-${model}.pkl.epoch00${epoch_nb} \
--truncate 0 \
--final_frame_offset 0 \
--result "trained0s_predict0s_hflip_luc.txt" \
--jaad_train "/home/michels/IntentionHaziqReplication/luc_data/singletxt_train_0s_luc" --jaad_val "/home/michels/IntentionHaziqReplication/luc_data/singletxt_val_0s_luc" --jaad_pre_train "/home/michels/IntentionHaziqReplication/luc_data/singletxt_train_0s_luc"

srun python3 -m openpifpaf.eval --batch-size 1 --jaad_batch_size 1 \
--checkpoint outputs/resnet50block5-pif-paf-crm-edge401-${model}.pkl.epoch00${epoch_nb} \
--truncate 0 \
--final_frame_offset 0 \
--result "trained0s_predict1s_hflip_luc.txt" \
--jaad_train "/home/michels/IntentionHaziqReplication/luc_data/singletxt_train_1s_luc" --jaad_val "/home/michels/IntentionHaziqReplication/luc_data/singletxt_val_1s_luc" --jaad_pre_train "/home/michels/IntentionHaziqReplication/luc_data/singletxt_train_1s_luc"

srun python3 -m openpifpaf.eval --batch-size 1 --jaad_batch_size 1 \
--checkpoint outputs/resnet50block5-pif-paf-crm-edge401-${model}.pkl.epoch00${epoch_nb} \
--truncate 0 \
--final_frame_offset 0 \
--result "trained0s_predict2s_hflip_luc.txt" \
--jaad_train "/home/michels/IntentionHaziqReplication/luc_data/singletxt_train_2s_luc" --jaad_val "/home/michels/IntentionHaziqReplication/luc_data/singletxt_val_2s_luc" --jaad_pre_train "/home/michels/IntentionHaziqReplication/luc_data/singletxt_train_2s_luc"

srun python3 -m openpifpaf.eval --batch-size 1 --jaad_batch_size 1 \
--checkpoint outputs/resnet50block5-pif-paf-crm-edge401-${model}.pkl.epoch00${epoch_nb} \
--truncate 0 \
--final_frame_offset 0 \
--result "trained0s_predict3s_hflip_luc.txt" \
--jaad_train "/home/michels/IntentionHaziqReplication/luc_data/singletxt_train_3s_luc" --jaad_val "/home/michels/IntentionHaziqReplication/luc_data/singletxt_val_3s_luc" --jaad_pre_train "/home/michels/IntentionHaziqReplication/luc_data/singletxt_train_3s_luc"

srun python3 -m openpifpaf.eval --batch-size 1 --jaad_batch_size 1 \
--checkpoint outputs/resnet50block5-pif-paf-crm-edge401-${model}.pkl.epoch00${epoch_nb} \
--truncate 0 \
--final_frame_offset 0 \
--result "trained0s_predict4s_hflip_luc.txt" \
--jaad_train "/home/michels/IntentionHaziqReplication/luc_data/singletxt_train_4s_luc" --jaad_val "/home/michels/IntentionHaziqReplication/luc_data/singletxt_val_4s_luc" --jaad_pre_train "/home/michels/IntentionHaziqReplication/luc_data/singletxt_train_4s_luc"


deactivate

echo "Success"

date