#!/bin/bash
#SBATCH --job-name=test      # Job name
#SBATCH --mail-type=ALL              # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=3gmichels@gmail.com    # Where to send mail	
#SBATCH --nodes=1                    # Run all processes on a single node	
#SBATCH --ntasks=1                   # Run a single task		
#SBATCH --cpus-per-task=1            # Number of CPU cores per task
#SBATCH --mem=25gb                    # Job memory request
#SBATCH --time=00:15:00              # Time limit hrs:min:sec
#SBATCH --gres=gpu:1				 # Amount of GPUs

pwd; hostname; date

echo "Evaluating Haziq's model"

module purge
module load gcc/8.4.0-cuda python/3.7.7
source /home/michels/venvs/haziq/bin/activate

srun python3 -m openpifpaf.eval --batch-size 1 --jaad_batch_size 1 \
--checkpoint outputs/resnet50block5-pif-paf-crm-edge401-210306-050654.pkl.epoch006 \
--truncate 0 \
--final_frame_offset 0 \
--result "test_luc.txt" \
--jaad_train "/home/michels/annotations_luc/singletext_train_0s" --jaad_val "/home/michels/annotations_luc/singletext_val_0s" --jaad_pre_train "/home/michels/annotations/singletxt_pre_train_4s"


deactivate

echo "Success"

date