#!/bin/bash
#SBATCH --job-name=test_trunc      # Job name
#SBATCH --mail-type=ALL              # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=3gmichels@gmail.com    # Where to send mail	
#SBATCH --nodes=1                    # Run all processes on a single node	
#SBATCH --ntasks=1                   # Run a single task		
#SBATCH --cpus-per-task=1            # Number of CPU cores per task
#SBATCH --mem=30gb                    # Job memory request
#SBATCH --time=04:00:00              # Time limit hrs:min:sec
#SBATCH --gres=gpu:1				 # Amount of GPUs
#SBATCH --output=slurm-full_hazik_eval_COCO_x2_HFlip-%j.out  # Output name

pwd; hostname; date

echo "Evaluating Haziq's model"

module purge
module load gcc/8.4.0-cuda python/3.7.7
source /home/michels/venvs/haziq/bin/activate

srun python3 -m openpifpaf.eval --batch-size 1 --jaad_batch_size 1 \
--checkpoint outputs/resnet50block5-pif-paf-crm-edge401-210406-113617.pkl.epoch002 \
--truncate 0 \
--final_frame_offset 0 \
--result "trained0s_predict0s_truncated_hflip.txt" \
--jaad_train "/home/michels/annotations/singletxt_train_0s_truncated" --jaad_val "/home/michels/annotations/singletxt_val_0s_truncated" --jaad_pre_train "/home/michels/annotations/singletxt_pre_train_0s_truncated"

srun python3 -m openpifpaf.eval --batch-size 1 --jaad_batch_size 1 \
--checkpoint outputs/resnet50block5-pif-paf-crm-edge401-210406-113617.pkl.epoch002 \
--truncate 0 \
--final_frame_offset 0 \
--result "trained0s_predict1s_truncated_hflip.txt" \
--jaad_train "/home/michels/annotations/singletxt_train_1s_truncated" --jaad_val "/home/michels/annotations/singletxt_val_1s_truncated" --jaad_pre_train "/home/michels/annotations/singletxt_pre_train_1s_truncated"

srun python3 -m openpifpaf.eval --batch-size 1 --jaad_batch_size 1 \
--checkpoint outputs/resnet50block5-pif-paf-crm-edge401-210406-113617.pkl.epoch002 \
--truncate 0 \
--final_frame_offset 0 \
--result "trained0s_predict2s_truncated_hflip.txt" \
--jaad_train "/home/michels/annotations/singletxt_train_2s_truncated" --jaad_val "/home/michels/annotations/singletxt_val_2s_truncated" --jaad_pre_train "/home/michels/annotations/singletxt_pre_train_2s_truncated"

srun python3 -m openpifpaf.eval --batch-size 1 --jaad_batch_size 1 \
--checkpoint outputs/resnet50block5-pif-paf-crm-edge401-210406-113617.pkl.epoch002 \
--truncate 0 \
--final_frame_offset 0 \
--result "trained0s_predict3s_truncated_hflip.txt" \
--jaad_train "/home/michels/annotations/singletxt_train_3s_truncated" --jaad_val "/home/michels/annotations/singletxt_val_3s_truncated" --jaad_pre_train "/home/michels/annotations/singletxt_pre_train_3s_truncated"

srun python3 -m openpifpaf.eval --batch-size 1 --jaad_batch_size 1 \
--checkpoint outputs/resnet50block5-pif-paf-crm-edge401-210406-113617.pkl.epoch002 \
--truncate 0 \
--final_frame_offset 0 \
--result "trained0s_predict4s_truncated_hflip.txt" \
--jaad_train "/home/michels/annotations/singletxt_train_4s_truncated" --jaad_val "/home/michels/annotations/singletxt_val_4s_truncated" --jaad_pre_train "/home/michels/annotations/singletxt_pre_train_4s_truncated"



deactivate

echo "Success"

date