#!/bin/bash
#SBATCH --job-name=test      # Job name
#SBATCH --mail-type=ALL              # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=3gmichels@gmail.com    # Where to send mail	
#SBATCH --nodes=1                    # Run all processes on a single node	
#SBATCH --ntasks=1                   # Run a single task		
#SBATCH --cpus-per-task=1            # Number of CPU cores per task
#SBATCH --mem=25gb                    # Job memory request
#SBATCH --time=00:04:00              # Time limit hrs:min:sec
#SBATCH --gres=gpu:1				 # Amount of GPUs
#SBATCH --output=slurm-luc_test-%j.out	# Output name


pwd; hostname; date

echo "Evaluating Haziq's model"

module purge
module load gcc/8.4.0-cuda python/3.7.7
source /home/michels/venvs/haziq/bin/activate

srun python3 -m openpifpaf.eval --batch-size 1 --jaad_batch_size 1 \
--checkpoint outputs/resnet50block5-pif-paf-crm-edge401-190525-002719.pkl.epoch006 \
--truncate 0 \
--final_frame_offset 0 \
--result "trained4s_predict1s_luc_truncated.txt" \
--jaad_train "/home/michels/IntentionHaziqReplication/luc_data/singletxt_train_1s_luc_truncated" --jaad_val "/home/michels/IntentionHaziqReplication/luc_data/singletxt_val_1s_luc_truncated" --jaad_pre_train "/home/michels/annotations/singletxt_pre_train_1s_truncated"

srun python3 -m openpifpaf.eval --batch-size 1 --jaad_batch_size 1 \
--checkpoint outputs/resnet50block5-pif-paf-crm-edge401-190525-002719.pkl.epoch006 \
--truncate 0 \
--final_frame_offset 0 \
--result "trained4s_predict4s_luc.txt" \
--jaad_train "/home/michels/IntentionHaziqReplication/luc_data/singletxt_train_4s_luc" --jaad_val "/home/michels/IntentionHaziqReplication/luc_data/singletxt_val_4s_luc" --jaad_pre_train "/home/michels/annotations/singletxt_pre_train_4s"

deactivate

echo "Success_luc"

date