#!/bin/bash
#SBATCH --job-name=test_epoch_3_7      # Job name
#SBATCH --mail-type=ALL              # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=3gmichels@gmail.com    # Where to send mail	
#SBATCH --nodes=1                    # Run all processes on a single node	
#SBATCH --ntasks=1                   # Run a single task		
#SBATCH --cpus-per-task=1            # Number of CPU cores per task
#SBATCH --mem=25gb                    # Job memory request
#SBATCH --time=20:00:00              # Time limit hrs:min:sec
#SBATCH --gres=gpu:1				 # Amount of GPUs
#SBATCH --output=slurm-luc_test_epoch-%j.out	# Output name


pwd; hostname; date

echo "Evaluating Haziq's model"

module purge
module load gcc/8.4.0-cuda python/3.7.7
source /home/michels/venvs/haziq/bin/activate

srun python3 -m openpifpaf.eval --batch-size 1 --jaad_batch_size 1 \
--checkpoint outputs/resnet50block5-pif-paf-crm-edge401-210318-062705.pkl.epoch003 \
--truncate 0 \
--final_frame_offset 0 \
--result "trained4s_predict1s_truncated_3.txt" \
--jaad_train "/home/michels/annotations/singletxt_pre_train_1s_truncated" --jaad_val "/home/michels/annotations/singletxt_val_1s_truncated" --jaad_pre_train "/home/michels/annotations/singletxt_pre_train_0s_truncated"

srun python3 -m openpifpaf.eval --batch-size 1 --jaad_batch_size 1 \
--checkpoint outputs/resnet50block5-pif-paf-crm-edge401-210318-062705.pkl.epoch003 \
--truncate 0 \
--final_frame_offset 0 \
--result "trained4s_predict1s_3.txt" \
--jaad_train "/home/michels/annotations/singletxt_pre_train_1s" --jaad_val "/home/michels/annotations/singletxt_val_1s" --jaad_pre_train "/home/michels/annotations/singletxt_pre_train_0s"

srun python3 -m openpifpaf.eval --batch-size 1 --jaad_batch_size 1 \
--checkpoint outputs/resnet50block5-pif-paf-crm-edge401-210318-062705.pkl.epoch003 \
--truncate 0 \
--final_frame_offset 0 \
--result "trained4s_predict4s_truncated_3.txt" \
--jaad_train "/home/michels/annotations/singletxt_pre_train_4s_truncated" --jaad_val "/home/michels/annotations/singletxt_val_4s_truncated" --jaad_pre_train "/home/michels/annotations/singletxt_pre_train_0s_truncated"

srun python3 -m openpifpaf.eval --batch-size 1 --jaad_batch_size 1 \
--checkpoint outputs/resnet50block5-pif-paf-crm-edge401-210318-062705.pkl.epoch003 \
--truncate 0 \
--final_frame_offset 0 \
--result "trained4s_predict4s_3.txt" \
--jaad_train "/home/michels/annotations/singletxt_pre_train_4s" --jaad_val "/home/michels/annotations/singletxt_val_4s" --jaad_pre_train "/home/michels/annotations/singletxt_pre_train_0s"


srun python3 -m openpifpaf.eval --batch-size 1 --jaad_batch_size 1 \
--checkpoint outputs/resnet50block5-pif-paf-crm-edge401-210318-062705.pkl.epoch004 \
--truncate 0 \
--final_frame_offset 0 \
--result "trained4s_predict1s_truncated_4.txt" \
--jaad_train "/home/michels/annotations/singletxt_pre_train_1s_truncated" --jaad_val "/home/michels/annotations/singletxt_val_1s_truncated" --jaad_pre_train "/home/michels/annotations/singletxt_pre_train_0s_truncated"

srun python3 -m openpifpaf.eval --batch-size 1 --jaad_batch_size 1 \
--checkpoint outputs/resnet50block5-pif-paf-crm-edge401-210318-062705.pkl.epoch004 \
--truncate 0 \
--final_frame_offset 0 \
--result "trained4s_predict1s_4.txt" \
--jaad_train "/home/michels/annotations/singletxt_pre_train_1s" --jaad_val "/home/michels/annotations/singletxt_val_1s" --jaad_pre_train "/home/michels/annotations/singletxt_pre_train_0s"

srun python3 -m openpifpaf.eval --batch-size 1 --jaad_batch_size 1 \
--checkpoint outputs/resnet50block5-pif-paf-crm-edge401-210318-062705.pkl.epoch004 \
--truncate 0 \
--final_frame_offset 0 \
--result "trained4s_predict4s_truncated_4.txt" \
--jaad_train "/home/michels/annotations/singletxt_pre_train_4s_truncated" --jaad_val "/home/michels/annotations/singletxt_val_4s_truncated" --jaad_pre_train "/home/michels/annotations/singletxt_pre_train_0s_truncated"

srun python3 -m openpifpaf.eval --batch-size 1 --jaad_batch_size 1 \
--checkpoint outputs/resnet50block5-pif-paf-crm-edge401-210318-062705.pkl.epoch004 \
--truncate 0 \
--final_frame_offset 0 \
--result "trained4s_predict4s_4.txt" \
--jaad_train "/home/michels/annotations/singletxt_pre_train_4s" --jaad_val "/home/michels/annotations/singletxt_val_4s" --jaad_pre_train "/home/michels/annotations/singletxt_pre_train_0s"


srun python3 -m openpifpaf.eval --batch-size 1 --jaad_batch_size 1 \
--checkpoint outputs/resnet50block5-pif-paf-crm-edge401-210318-062705.pkl.epoch005 \
--truncate 0 \
--final_frame_offset 0 \
--result "trained4s_predict1s_truncated_5.txt" \
--jaad_train "/home/michels/annotations/singletxt_pre_train_1s_truncated" --jaad_val "/home/michels/annotations/singletxt_val_1s_truncated" --jaad_pre_train "/home/michels/annotations/singletxt_pre_train_0s_truncated"

srun python3 -m openpifpaf.eval --batch-size 1 --jaad_batch_size 1 \
--checkpoint outputs/resnet50block5-pif-paf-crm-edge401-210318-062705.pkl.epoch005 \
--truncate 0 \
--final_frame_offset 0 \
--result "trained4s_predict1s_5.txt" \
--jaad_train "/home/michels/annotations/singletxt_pre_train_1s" --jaad_val "/home/michels/annotations/singletxt_val_1s" --jaad_pre_train "/home/michels/annotations/singletxt_pre_train_0s"

srun python3 -m openpifpaf.eval --batch-size 1 --jaad_batch_size 1 \
--checkpoint outputs/resnet50block5-pif-paf-crm-edge401-210318-062705.pkl.epoch005 \
--truncate 0 \
--final_frame_offset 0 \
--result "trained4s_predict4s_truncated_5.txt" \
--jaad_train "/home/michels/annotations/singletxt_pre_train_4s_truncated" --jaad_val "/home/michels/annotations/singletxt_val_4s_truncated" --jaad_pre_train "/home/michels/annotations/singletxt_pre_train_0s_truncated"

srun python3 -m openpifpaf.eval --batch-size 1 --jaad_batch_size 1 \
--checkpoint outputs/resnet50block5-pif-paf-crm-edge401-210318-062705.pkl.epoch005 \
--truncate 0 \
--final_frame_offset 0 \
--result "trained4s_predict4s_5.txt" \
--jaad_train "/home/michels/annotations/singletxt_pre_train_4s" --jaad_val "/home/michels/annotations/singletxt_val_4s" --jaad_pre_train "/home/michels/annotations/singletxt_pre_train_0s"

srun python3 -m openpifpaf.eval --batch-size 1 --jaad_batch_size 1 \
--checkpoint outputs/resnet50block5-pif-paf-crm-edge401-210318-062705.pkl.epoch006 \
--truncate 0 \
--final_frame_offset 0 \
--result "trained4s_predict1s_truncated_6.txt" \
--jaad_train "/home/michels/annotations/singletxt_pre_train_1s_truncated" --jaad_val "/home/michels/annotations/singletxt_val_1s_truncated" --jaad_pre_train "/home/michels/annotations/singletxt_pre_train_0s_truncated"

srun python3 -m openpifpaf.eval --batch-size 1 --jaad_batch_size 1 \
--checkpoint outputs/resnet50block5-pif-paf-crm-edge401-210318-062705.pkl.epoch006 \
--truncate 0 \
--final_frame_offset 0 \
--result "trained4s_predict1s_6.txt" \
--jaad_train "/home/michels/annotations/singletxt_pre_train_1s" --jaad_val "/home/michels/annotations/singletxt_val_1s" --jaad_pre_train "/home/michels/annotations/singletxt_pre_train_0s"

srun python3 -m openpifpaf.eval --batch-size 1 --jaad_batch_size 1 \
--checkpoint outputs/resnet50block5-pif-paf-crm-edge401-210318-062705.pkl.epoch006 \
--truncate 0 \
--final_frame_offset 0 \
--result "trained4s_predict4s_truncated_6.txt" \
--jaad_train "/home/michels/annotations/singletxt_pre_train_4s_truncated" --jaad_val "/home/michels/annotations/singletxt_val_4s_truncated" --jaad_pre_train "/home/michels/annotations/singletxt_pre_train_0s_truncated"

srun python3 -m openpifpaf.eval --batch-size 1 --jaad_batch_size 1 \
--checkpoint outputs/resnet50block5-pif-paf-crm-edge401-210318-062705.pkl.epoch006 \
--truncate 0 \
--final_frame_offset 0 \
--result "trained4s_predict4s_6.txt" \
--jaad_train "/home/michels/annotations/singletxt_pre_train_4s" --jaad_val "/home/michels/annotations/singletxt_val_4s" --jaad_pre_train "/home/michels/annotations/singletxt_pre_train_0s"

srun python3 -m openpifpaf.eval --batch-size 1 --jaad_batch_size 1 \
--checkpoint outputs/resnet50block5-pif-paf-crm-edge401-210318-062705.pkl.epoch007 \
--truncate 0 \
--final_frame_offset 0 \
--result "trained4s_predict1s_truncated_7.txt" \
--jaad_train "/home/michels/annotations/singletxt_pre_train_1s_truncated" --jaad_val "/home/michels/annotations/singletxt_val_1s_truncated" --jaad_pre_train "/home/michels/annotations/singletxt_pre_train_0s_truncated"

srun python3 -m openpifpaf.eval --batch-size 1 --jaad_batch_size 1 \
--checkpoint outputs/resnet50block5-pif-paf-crm-edge401-210318-062705.pkl.epoch007 \
--truncate 0 \
--final_frame_offset 0 \
--result "trained4s_predict1s_7.txt" \
--jaad_train "/home/michels/annotations/singletxt_pre_train_1s" --jaad_val "/home/michels/annotations/singletxt_val_1s" --jaad_pre_train "/home/michels/annotations/singletxt_pre_train_0s"

srun python3 -m openpifpaf.eval --batch-size 1 --jaad_batch_size 1 \
--checkpoint outputs/resnet50block5-pif-paf-crm-edge401-210318-062705.pkl.epoch007 \
--truncate 0 \
--final_frame_offset 0 \
--result "trained4s_predict4s_truncated_7.txt" \
--jaad_train "/home/michels/annotations/singletxt_pre_train_4s_truncated" --jaad_val "/home/michels/annotations/singletxt_val_4s_truncated" --jaad_pre_train "/home/michels/annotations/singletxt_pre_train_0s_truncated"

srun python3 -m openpifpaf.eval --batch-size 1 --jaad_batch_size 1 \
--checkpoint outputs/resnet50block5-pif-paf-crm-edge401-210318-062705.pkl.epoch007 \
--truncate 0 \
--final_frame_offset 0 \
--result "trained4s_predict4s_7.txt" \
--jaad_train "/home/michels/annotations/singletxt_pre_train_4s" --jaad_val "/home/michels/annotations/singletxt_val_4s" --jaad_pre_train "/home/michels/annotations/singletxt_pre_train_0s"





deactivate

echo "Success_luc"

date