#!/bin/bash
#SBATCH --job-name=test      # Job name
#SBATCH --mail-type=ALL              # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=3gmichels@gmail.com    # Where to send mail	
#SBATCH --nodes=1                    # Run all processes on a single node	
#SBATCH --ntasks=1                   # Run a single task		
#SBATCH --cpus-per-task=1            # Number of CPU cores per task
#SBATCH --mem=25gb                    # Job memory request
#SBATCH --time=00:15:00              # Time limit hrs:min:sec
#SBATCH --gres=gpu:1				 # Amount of GPUs

pwd; hostname; date

echo "Evaluating Haziq's model"

module purge
module load gcc/8.4.0-cuda python/3.7.7
source /home/michels/venvs/haziq/bin/activate

srun python3 -m openpifpaf.eval --batch-size 1 --jaad_batch_size 1 \
--checkpoint outputs/resnet50block5-pif-paf-crm-edge401-210310-021354.pkl.epoch006 \
--truncate 0 \
--final_frame_offset 0 \
--result "trained4s_luc_predict1s_luc_truncated.txt" \
--jaad_train "/home/michels/annotations/singletxt_pre_train_1s_truncated" --jaad_val "/home/michels/IntentionHaziqReplication/luc_data/singletxt_val_1s_luc_truncated" --jaad_pre_train "/home/michels/annotations/singletxt_pre_train_1s_luc_truncated"

srun python3 -m openpifpaf.eval --batch-size 1 --jaad_batch_size 1 \
--checkpoint outputs/resnet50block5-pif-paf-crm-edge401-210310-021354.pkl.epoch006 \
--truncate 0 \
--final_frame_offset 0 \
--result "trained4s_luc_predict2s_luc_truncated.txt" \
--jaad_train "/home/michels/annotations/singletxt_pre_train_2s_truncated" --jaad_val "/home/michels/IntentionHaziqReplication/luc_data/singletxt_val_2s_luc_truncated" --jaad_pre_train "/home/michels/annotations/singletxt_pre_train_2s_luc_truncated"

srun python3 -m openpifpaf.eval --batch-size 1 --jaad_batch_size 1 \
--checkpoint outputs/resnet50block5-pif-paf-crm-edge401-210310-021354.pkl.epoch006 \
--truncate 0 \
--final_frame_offset 0 \
--result "trained4s_luc_predict3s_luc_truncated.txt" \
--jaad_train "/home/michels/annotations/singletxt_pre_train_3s_truncated" --jaad_val "/home/michels/IntentionHaziqReplication/luc_data/singletxt_val_3s_luc_truncated" --jaad_pre_train "/home/michels/annotations/singletxt_pre_train_3s_luc_truncated"

srun python3 -m openpifpaf.eval --batch-size 1 --jaad_batch_size 1 \
--checkpoint outputs/resnet50block5-pif-paf-crm-edge401-210310-021354.pkl.epoch006 \
--truncate 0 \
--final_frame_offset 0 \
--result "trained4s_luc_predict4s_luc_truncated.txt" \
--jaad_train "/home/michels/annotations/singletxt_pre_train_4s_truncated" --jaad_val "/home/michels/IntentionHaziqReplication/luc_data/singletxt_val_4s_luc_truncated" --jaad_pre_train "/home/michels/annotations/singletxt_pre_train_4s_luc_truncated"

srun python3 -m openpifpaf.eval --batch-size 1 --jaad_batch_size 1 \
--checkpoint outputs/resnet50block5-pif-paf-crm-edge401-210310-021354.pkl.epoch006 \
--truncate 0 \
--final_frame_offset 0 \
--result "trained4s_luc_predict0s.txt" \
--jaad_train "/home/michels/annotations/singletxt_pre_train_0s" --jaad_val "/home/michels/IntentionHaziqReplication/luc_data/singletxt_val_0s_luc" --jaad_pre_train "/home/michels/annotations/singletxt_pre_train_0s_luc"

srun python3 -m openpifpaf.eval --batch-size 1 --jaad_batch_size 1 \
--checkpoint outputs/resnet50block5-pif-paf-crm-edge401-210310-021354.pkl.epoch006 \
--truncate 0 \
--final_frame_offset 0 \
--result "trained4s_luc_predict1s.txt" \
--jaad_train "/home/michels/annotations/singletxt_pre_train_1s" --jaad_val "/home/michels/IntentionHaziqReplication/luc_data/singletxt_val_1s_luc" --jaad_pre_train "/home/michels/annotations/singletxt_pre_train_1s_luc"

srun python3 -m openpifpaf.eval --batch-size 1 --jaad_batch_size 1 \
--checkpoint outputs/resnet50block5-pif-paf-crm-edge401-210310-021354.pkl.epoch006 \
--truncate 0 \
--final_frame_offset 0 \
--result "trained4s_luc_predict2s.txt" \
--jaad_train "/home/michels/annotations/singletxt_pre_train_2s" --jaad_val "/home/michels/IntentionHaziqReplication/luc_data/singletxt_val_2s_luc" --jaad_pre_train "/home/michels/annotations/singletxt_pre_train_2s_luc"

srun python3 -m openpifpaf.eval --batch-size 1 --jaad_batch_size 1 \
--checkpoint outputs/resnet50block5-pif-paf-crm-edge401-210310-021354.pkl.epoch006 \
--truncate 0 \
--final_frame_offset 0 \
--result "trained4s_luc_predict3s.txt" \
--jaad_train "/home/michels/annotations/singletxt_pre_train_3s" --jaad_val "/home/michels/IntentionHaziqReplication/luc_data/singletxt_val_3s_luc" --jaad_pre_train "/home/michels/annotations/singletxt_pre_train_3s_luc"

srun python3 -m openpifpaf.eval --batch-size 1 --jaad_batch_size 1 \
--checkpoint outputs/resnet50block5-pif-paf-crm-edge401-210310-021354.pkl.epoch006 \
--truncate 0 \
--final_frame_offset 0 \
--result "trained4s_luc_predict4s.txt" \
--jaad_train "/home/michels/annotations/singletxt_pre_train_4s" --jaad_val "/home/michels/IntentionHaziqReplication/luc_data/singletxt_val_4s_luc" --jaad_pre_train "/home/michels/annotations/singletxt_pre_train_4s_luc"

deactivate

echo "Success_luc"

date